import("//build/lite/config/component/lite_component.gni")

lite_component("app") {
  features = [ 
    #"1.0_Hello_World:Hello_World",
    #"2.0_LED:LED",
    #"3.0_Electromagnetic_relays_Thread:EC_Thread",
    #"4.0_Buzzer:Buzzer",
    #"5.0_Fan:Fan",
    #"6.0_Key_Interrupt:Key_Interrupt",
    #"7.0_LED_Pwm:LED_Pwm",  
    #"8.0_Uart_GPS:Uart_GPS",
    #"9.0_Experiment_Stage1:Experiment_Stage1",
    #"10.0_Adc:Adc",
    #"11.0_OLED:OLED",
    #"12.0_Sht20:Sht20",
    #"13.0_AP3216c:AP3216c",
    #"14.0_MPU6050:MPU6050",
    #"15.0_NFC:NFC",
    #"16.0_Experiment_Stage2:Experiment_Stage2",
    #"17.0_WIFI:WIFI",
    #"18.0_MQTT:MQTT",
    "19.0_Experiment_Stage3:Experiment_Stage3"
  ]
}